using Stump.Core.Reflection;
using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Challenges
{
    [D2OClass("Challenge", "com.ankamagames.dofus.datacenter.challenges", true), TableName("challenges")]
    public class ChallengeRecord : IAutoGeneratedRecord, ISaveIntercepter, IAssignedByD2O
    {
        // FIELDS
        private string m_name;
        private string m_description;

        // PROPERTIES
        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }
        public uint NameId
        {
            get;
            set;
        }
        public string Name
        {
            get
            {
                if (this.m_name == null)
                {
                    this.m_name = Singleton<TextManager>.Instance.GetText(this.NameId);
                }
                return this.m_name;
            }
        }
        public uint DescriptionId
        {
            get;
            set;
        }
        public string Description
        {
            get
            {
                if (this.m_description == null)
                {
                    this.m_description = Singleton<TextManager>.Instance.GetText(this.DescriptionId);
                }
                return this.m_description;
            }
        }
        public bool Hidden
        {
            get;
            set;
        }
        public int MinBonus
        {
            get;
            set;
        }
        public int MaxBonus
        {
            get;
            set;
        }

        // CONSTRUCTORS

        // METHODS
        public void BeforeSave(bool insert)
        {
        }

        public void AssignFields(object d2oObject)
        {
            Challenge challenge = (Challenge)d2oObject;
            this.Id = challenge.id;
            this.NameId = challenge.nameId;
            this.DescriptionId = challenge.descriptionId;
        }
    }
}
