using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System.Linq;
namespace Stump.Server.WorldServer.Database.Guilds
{
	[TableName("guilds")]
	public class GuildRecord : IAutoGeneratedRecord
	{
		private int[] m_spells;
		private string m_spellsCSV;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		[Ignore]
		public bool IsNew
		{
			get;
			set;
		}
        public int? AllianceId
        {
            get;
            set;
        }
		public System.DateTime CreationDate
		{
			get;
			set;
		}
		public string Name
		{
			get;
			set;
		}
		public long Experience
		{
			get;
			set;
		}
		public uint Boost
		{
			get;
			set;
		}
		public int Prospecting
		{
			get;
			set;
		}
		public int Wisdom
		{
			get;
			set;
		}
		public int Pods
		{
			get;
			set;
		}
		public int MaxTaxCollectors
		{
			get;
			set;
		}
		[Ignore]
		public int[] Spells
		{
			get
			{
				return this.m_spells;
			}
			set
			{
				this.m_spells = value;
				this.m_spellsCSV = this.m_spells.ToCSV(",");
			}
		}
		[NullString]
		public string SpellsCSV
		{
			get
			{
				return this.m_spellsCSV;
			}
			set
			{
				this.m_spellsCSV = value;
                this.m_spells = ((!string.IsNullOrEmpty(this.m_spellsCSV)) ? this.m_spellsCSV.FromCSV<int>(",").ToArray<int>() : new int[0]);
			}
		}
		public short EmblemBackgroundShape
		{
			get;
			set;
		}
		public int EmblemBackgroundColor
		{
			get;
			set;
		}
		public short EmblemForegroundShape
		{
			get;
			set;
		}
		public int EmblemForegroundColor
		{
			get;
			set;
		}
	}
}
