using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Effects
{
	[D2OClass("Effect", "com.ankamagames.dofus.datacenter.effects", true), TableName("effects_templates")]
	public class EffectTemplate : IAutoGeneratedRecord, IAssignedByD2O
	{
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public uint DescriptionId
		{
			get;
			set;
		}
		public int IconId
		{
			get;
			set;
		}
		public int Characteristic
		{
			get;
			set;
		}
		public uint Category
		{
			get;
			set;
		}
		public string Operator
		{
			get;
			set;
		}
		public bool ShowInTooltip
		{
			get;
			set;
		}
		public bool UseDice
		{
			get;
			set;
		}
		public bool ForceMinMax
		{
			get;
			set;
		}
		public bool Boost
		{
			get;
			set;
		}
		public bool Active
		{
			get;
			set;
		}
		public bool ShowInSet
		{
			get;
			set;
		}
		public int BonusType
		{
			get;
			set;
		}
		public bool UseInFight
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			Effect effect = (Effect)d2oObject;
			this.Id = effect.id;
			this.DescriptionId = effect.descriptionId;
			this.IconId = effect.iconId;
			this.Characteristic = effect.characteristic;
			this.Category = effect.category;
			this.Operator = effect.@operator ?? "";
			this.ShowInTooltip = effect.showInTooltip;
			this.UseDice = effect.useDice;
			this.ForceMinMax = effect.forceMinMax;
			this.Boost = effect.boost;
			this.Active = effect.active;
			this.ShowInSet = effect.showInSet;
			this.BonusType = effect.bonusType;
			this.UseInFight = effect.useInFight;
		}
	}
}
