using Stump.Core.IO;
using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items.Templates
{
	[D2OClass("Pet", "com.ankamagames.dofus.datacenter.pets", true), TableName("items_pets")]
	public class PetTemplate : IAutoGeneratedRecord, ISaveIntercepter, IAssignedByD2O
	{
		private int[] m_foodItems;
		private string m_foodItemsCSV;
		private int[] m_foodTypes;
		private string m_foodTypesCSV;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public string FoodItemsCSV
		{
			get
			{
				return this.m_foodItemsCSV;
			}
			set
			{
				this.m_foodItemsCSV = value;
				this.m_foodItems = value.FromCSV<int>(",");
			}
		}
		[Ignore]
		public int[] FoodItems
		{
			get
			{
				return this.m_foodItems;
			}
			set
			{
				this.m_foodItems = value;
				this.m_foodItemsCSV = value.ToCSV(",");
			}
		}
		public string FoodTypesCSV
		{
			get
			{
				return this.m_foodTypesCSV;
			}
			set
			{
				this.m_foodTypesCSV = value;
                this.m_foodTypes = value.FromCSV<int>(",");
			}
		}
		[Ignore]
		public int[] FoodTypes
		{
			get
			{
				return this.m_foodTypes;
			}
			set
			{
				this.m_foodTypes = value;
				this.m_foodTypesCSV = value.ToCSV(",");
			}
		}
		public void AssignFields(object d2oObject)
		{
			Pet pet = (Pet)d2oObject;
			this.Id = pet.id;
			this.FoodItems = pet.foodItems.ToArray();
			this.FoodTypes = pet.foodTypes.ToArray();
		}
		public void BeforeSave(bool insert)
		{
			this.m_foodItemsCSV = this.m_foodItems.ToCSV(",");
			this.m_foodTypesCSV = this.m_foodTypes.ToCSV(",");
		}
	}
}
