using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Interactives
{
	[TableName("interactives_spawns_skills")]
	public class InteractiveSpawnSkills : IAutoGeneratedRecord
	{
		[PrimaryKey("Id", true)]
		public int Id
		{
			get;
			set;
		}
		[Column("InteractiveSpawnId"), Index]
		public int InteractiveSpawnId
		{
			get;
			set;
		}
		[Column("SkillId")]
		public int SkillId
		{
			get;
			set;
		}
	}
}
