using Stump.Core.Reflection;
using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Interactives
{
	[D2OClass("Interactive", "com.ankamagames.dofus.datacenter.interactives", true), TableName("interactives_templates")]
	public class InteractiveTemplate : IAutoGeneratedRecord, IAssignedByD2O
	{
		private string m_name;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public InteractiveTypeEnum Type
		{
			get
			{
				return (InteractiveTypeEnum)this.Id;
			}
		}
		public uint NameId
		{
			get;
			set;
		}
		public string Name
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_name) == null)
				{
					arg_23_0 = (this.m_name = Singleton<TextManager>.Instance.GetText(this.NameId));
				}
				return arg_23_0;
			}
		}
		public int ActionId
		{
			get;
			set;
		}
		public bool DisplayTooltip
		{
			get;
			set;
		}
		[Ignore]
		public System.Collections.Generic.List<InteractiveSkillRecord> Skills
		{
			get;
			set;
		}
		public InteractiveTemplate()
		{
			this.Skills = new System.Collections.Generic.List<InteractiveSkillRecord>();
		}
		public void AssignFields(object d2oObject)
		{
			Interactive interactive = (Interactive)d2oObject;
			this.Id = interactive.id;
			this.NameId = interactive.nameId;
			this.ActionId = interactive.actionId;
			this.DisplayTooltip = interactive.displayTooltip;
		}
	}
}
