using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Accounts
{
	[TableName("accounts")]
	public class WorldAccount : IAutoGeneratedRecord
	{
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public string Nickname
		{
			get;
			set;
		}
		public System.DateTime? LastConnection
		{
			get;
			set;
		}
		[NullString]
		public string LastIp
		{
			get;
			set;
		}
		public int? ConnectedCharacter
		{
			get;
			set;
		}
		public int LastConnectionTimeStamp
		{
			get
			{
				return this.LastConnection.HasValue ? ((int)(System.DateTime.Now - this.LastConnection.Value).TotalHours) : 0;
			}
		}
	}
}
