using Stump.Core.Reflection;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Monsters
{
	[D2OClass("MonsterSuperRace", "com.ankamagames.dofus.datacenter.monsters", true), TableName("monsters_superraces")]
	public sealed class MonsterSuperRace : IAutoGeneratedRecord, IAssignedByD2O
	{
		private string m_name;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public uint NameId
		{
			get;
			set;
		}
		public string Name
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_name) == null)
				{
					arg_23_0 = (this.m_name = Singleton<TextManager>.Instance.GetText(this.NameId));
				}
				return arg_23_0;
			}
		}
		public void AssignFields(object d2oObject)
		{
			Stump.DofusProtocol.Classes.MonsterSuperRace monsterSuperRace = (Stump.DofusProtocol.Classes.MonsterSuperRace)d2oObject;
			this.Id = monsterSuperRace.id;
			this.NameId = monsterSuperRace.nameId;
		}
	}
}
