using Stump.Core.Reflection;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Spells;
using Stump.Server.WorldServer.Game.Actors.RolePlay.Monsters;

namespace Stump.Server.WorldServer.Database.Monsters
{
	[TableName("monsters_spells")]
	public class MonsterSpell : IAutoGeneratedRecord, ISpellRecord
	{
		private MonsterGrade m_monsterGrade;
		public int Id
		{
			get;
			set;
		}
		public int MonsterGradeId
		{
			get;
			set;
		}
		[Ignore]
		public MonsterGrade MonsterGrade
		{
			get
			{
				MonsterGrade arg_23_0;
				if ((arg_23_0 = this.m_monsterGrade) == null)
				{
					arg_23_0 = (this.m_monsterGrade = Singleton<MonsterManager>.Instance.GetMonsterGrade(this.MonsterGradeId));
				}
				return arg_23_0;
			}
			set
			{
				this.m_monsterGrade = value;
				this.MonsterGradeId = value.Id;
			}
		}
		public int SpellId
		{
			get;
			set;
		}
		[DefaultSetting(1)]
		public short Level
		{
			get;
			set;
		}
		public override string ToString()
		{
			return string.Concat(new object[]
			{
				(SpellIdEnum)this.SpellId,
				" (",
				this.SpellId,
				")"
			});
		}
	}
}
