using Stump.Core.Reflection;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;
using Stump.Server.WorldServer.Game.Actors.RolePlay.Monsters;

namespace Stump.Server.WorldServer.Database.Monsters
{
	[D2OClass("MonsterRace", "com.ankamagames.dofus.datacenter.monsters", true), TableName("monsters_races")]
	public class MonsterRace : IAutoGeneratedRecord, IAssignedByD2O
	{
		private string m_name;
		private MonsterSuperRace m_superRace;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public int SuperRaceId
		{
			get;
			set;
		}
		[Ignore]
		public MonsterSuperRace SuperRace
		{
			get
			{
				MonsterSuperRace arg_23_0;
				if ((arg_23_0 = this.m_superRace) == null)
				{
					arg_23_0 = (this.m_superRace = Singleton<MonsterManager>.Instance.GetSuperRace(this.SuperRaceId));
				}
				return arg_23_0;
			}
			set
			{
				this.m_superRace = value;
				this.SuperRaceId = value.Id;
			}
		}
		public uint NameId
		{
			get;
			set;
		}
		public string Name
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_name) == null)
				{
					arg_23_0 = (this.m_name = Singleton<TextManager>.Instance.GetText(this.NameId));
				}
				return arg_23_0;
			}
		}
		public void AssignFields(object d2oObject)
		{
			Stump.DofusProtocol.Classes.MonsterRace monsterRace = (Stump.DofusProtocol.Classes.MonsterRace)d2oObject;
			this.Id = monsterRace.id;
			this.NameId = monsterRace.nameId;
			this.SuperRaceId = monsterRace.superRaceId;
		}
	}
}
