using Stump.Core.Reflection;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Maps;

namespace Stump.Server.WorldServer.Database.Monsters
{
	[TableName("monsters_spawns")]
	public class MonsterSpawn : IAutoGeneratedRecord
	{
		private Map m_map;
		private SubArea m_subArea;
		public int Id
		{
			get;
			set;
		}
		public int? MapId
		{
			get;
			set;
		}
		[Ignore]
		public Map Map
		{
			get
			{
				Map result;
				if (!this.MapId.HasValue)
				{
					result = null;
				}
				else
				{
					Map arg_3F_0;
					if ((arg_3F_0 = this.m_map) == null)
					{
                        arg_3F_0 = (this.m_map = Singleton<Game.World>.Instance.GetMap(this.MapId.Value));
					}
					result = arg_3F_0;
				}
				return result;
			}
			set
			{
				this.m_map = value;
				if (value == null)
				{
					this.MapId = null;
				}
				else
				{
					this.MapId = new int?(value.Id);
				}
			}
		}
		public int? SubAreaId
		{
			get;
			set;
		}
		[Ignore]
		public SubArea SubArea
		{
			get
			{
				SubArea result;
				if (!this.SubAreaId.HasValue)
				{
					result = null;
				}
				else
				{
					SubArea arg_3F_0;
					if ((arg_3F_0 = this.m_subArea) == null)
					{
                        arg_3F_0 = (this.m_subArea = Singleton<Game.World>.Instance.GetSubArea(this.SubAreaId.Value));
					}
					result = arg_3F_0;
				}
				return result;
			}
			set
			{
				this.m_subArea = value;
				if (value == null)
				{
					this.SubAreaId = null;
				}
				else
				{
					this.SubAreaId = new int?(value.Id);
				}
			}
		}
		public int MonsterId
		{
			get;
			set;
		}
		[DefaultSetting(1.0)]
		public double Frequency
		{
			get;
			set;
		}
		[DefaultSetting(1)]
		public int MinGrade
		{
			get;
			set;
		}
		[DefaultSetting(5)]
		public int MaxGrade
		{
			get;
			set;
		}
	}
}
