using Stump.Core.Reflection;
using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.World
{
	[D2OClass("Area", "com.ankamagames.dofus.datacenter.world", true), TableName("world_areas")]
	public sealed class AreaRecord : IAutoGeneratedRecord, IAssignedByD2O
	{
		private string m_boundsCSV;
		private string m_name;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public uint NameId
		{
			get;
			set;
		}
		public string Name
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_name) == null)
				{
					arg_23_0 = (this.m_name = Singleton<TextManager>.Instance.GetText(this.NameId));
				}
				return arg_23_0;
			}
		}
		public int SuperAreaId
		{
			get;
			set;
		}
		public bool ContainHouses
		{
			get;
			set;
		}
		public bool ContainPaddocks
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			Area area = (Area)d2oObject;
			this.Id = area.id;
			this.NameId = area.nameId;
			this.SuperAreaId = area.superAreaId;
			this.ContainHouses = area.containHouses;
			this.ContainPaddocks = area.containPaddocks;
		}
	}
}
