using Stump.Core.Reflection;
using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.World
{
	[D2OClass("SuperArea", "com.ankamagames.dofus.datacenter.world", true), TableName("world_superareas")]
	public sealed class SuperAreaRecord : IAutoGeneratedRecord, IAssignedByD2O
	{
		private string m_name;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public uint NameId
		{
			get;
			set;
		}
		public string Name
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_name) == null)
				{
					arg_23_0 = (this.m_name = Singleton<TextManager>.Instance.GetText(this.NameId));
				}
				return arg_23_0;
			}
		}
		public uint WorldmapId
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			SuperArea superArea = (SuperArea)d2oObject;
			this.Id = superArea.id;
			this.NameId = superArea.nameId;
			this.WorldmapId = superArea.worldmapId;
		}
	}
}
