using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.World
{
	[D2OClass("WorldMap", "com.ankamagames.dofus.datacenter.world", true), TableName("world_worldmaps")]
	public sealed class WorldMapRecord : IAutoGeneratedRecord, IAssignedByD2O
	{
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public int OrigineX
		{
			get;
			set;
		}
		public int OrigineY
		{
			get;
			set;
		}
		public double MapWidth
		{
			get;
			set;
		}
		public double MapHeight
		{
			get;
			set;
		}
		public uint HorizontalChunck
		{
			get;
			set;
		}
		public uint VerticalChunck
		{
			get;
			set;
		}
		public bool ViewableEverywhere
		{
			get;
			set;
		}
		public double MinScale
		{
			get;
			set;
		}
		public double MaxScale
		{
			get;
			set;
		}
		public double StartScale
		{
			get;
			set;
		}
		public int CenterX
		{
			get;
			set;
		}
		public int CenterY
		{
			get;
			set;
		}
		public int TotalWidth
		{
			get;
			set;
		}
		public int TotalHeight
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			WorldMap worldMap = (WorldMap)d2oObject;
			this.Id = worldMap.id;
			this.OrigineX = worldMap.origineX;
			this.OrigineY = worldMap.origineY;
			this.MapWidth = worldMap.mapWidth;
			this.MapHeight = worldMap.mapHeight;
			this.HorizontalChunck = worldMap.horizontalChunck;
			this.VerticalChunck = worldMap.verticalChunck;
			this.ViewableEverywhere = worldMap.viewableEverywhere;
			this.MinScale = worldMap.minScale;
			this.MaxScale = worldMap.maxScale;
			this.StartScale = worldMap.startScale;
			this.CenterX = worldMap.centerX;
			this.CenterY = worldMap.centerY;
			this.TotalWidth = worldMap.totalWidth;
			this.TotalHeight = worldMap.totalHeight;
		}
	}
}
