using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Spells;

namespace Stump.Server.WorldServer.Database.Characters
{
	[TableName("characters_spells")]
	public class CharacterSpellRecord : IAutoGeneratedRecord, ISpellRecord
	{
		public int Id
		{
			get;
			set;
		}
		public int OwnerId
		{
			get;
			set;
		}
		public short Position
		{
			get;
			set;
		}
		public int SpellId
		{
			get;
			set;
		}
		public short Level
		{
			get;
			set;
		}
		public override string ToString()
		{
			return string.Concat(new object[]
			{
				(SpellIdEnum)this.SpellId,
				" (",
				this.SpellId,
				")"
			});
		}
	}
}
