using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Characters
{
	[TableName("experiences")]
	public class ExperienceTableEntry : IAutoGeneratedRecord
	{
		[PrimaryKey("Level", true)]
		public short Level
		{
			get;
			set;
		}
		public long? CharacterExp
		{
			get;
			set;
		}
		public long? GuildExp
		{
			get;
			set;
		}
		public long? MountExp
		{
			get;
			set;
		}
		public ushort? AlignmentHonor
		{
			get;
			set;
		}
	}
}
