using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Characters;

namespace Stump.Server.WorldServer.Database.Shortcuts
{
	[TableName("characters_shortcuts_items")]
	public class ItemShortcut : Shortcut, IAutoGeneratedRecord
	{
		private int m_itemTemplateId;
		private int m_itemGuid;
		public int ItemTemplateId
		{
			get
			{
				return this.m_itemTemplateId;
			}
			set
			{
				this.m_itemTemplateId = value;
				base.IsDirty = true;
			}
		}
		public int ItemGuid
		{
			get
			{
				return this.m_itemGuid;
			}
			set
			{
				this.m_itemGuid = value;
				base.IsDirty = true;
			}
		}
		public ItemShortcut()
		{
		}
		public ItemShortcut(CharacterRecord owner, int slot, int itemTemplateId, int itemGuid) : base(owner, slot)
		{
			this.ItemTemplateId = itemTemplateId;
			this.ItemGuid = itemGuid;
		}
		public override Stump.DofusProtocol.Types.Shortcut GetNetworkShortcut()
		{
            return new ShortcutObjectItem((sbyte)base.Slot, this.ItemGuid, this.ItemTemplateId);
		}
	}
}
