using Stump.DofusProtocol.Types;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Characters;

namespace Stump.Server.WorldServer.Database.Shortcuts
{
	[TableName("characters_shortcuts_spells")]
	public class SpellShortcut : Shortcut, IAutoGeneratedRecord
	{
		private short m_spellId;
		public short SpellId
		{
			get
			{
				return this.m_spellId;
			}
			set
			{
				this.m_spellId = value;
				base.IsDirty = true;
			}
		}
		public SpellShortcut()
		{
		}
		public SpellShortcut(CharacterRecord owner, int slot, short spellId) : base(owner, slot)
		{
			this.SpellId = spellId;
		}
		public override Stump.DofusProtocol.Types.Shortcut GetNetworkShortcut()
		{
            return new ShortcutSpell((sbyte)base.Slot, (ushort)this.SpellId);
		}
	}
}
