using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.BaseServer.IPC.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Stump.Core.IO;

namespace Stump.Server.AuthServer.Database
{
    [TableName("user_groups")]
    public class UserGroup : IAutoGeneratedRecord
    {
        private UserGroupData _data;
        private string _serversCSV;
        private List<int> _servers;

        public int Id { get; set; }

        public string Name { get; set; }

        public RoleEnum Role { get; set; }

        public bool IsGameMaster { get; set; }

        [NullString]
        public string ServersCSV
        {
            get
            {
                return _serversCSV;
            }
            set
            {
                _serversCSV = value;
                _servers = ((!string.IsNullOrEmpty(_serversCSV)) ? _serversCSV.FromCSV<int>(",").ToList<int>() : new List<int>());
            }
        }

        [Ignore]
        public List<int> Servers
        {
            get
            {
                return _servers;
            }
            set
            {
                _servers = value;
                _serversCSV = _serversCSV.ToCSV(",");
            }
        }

        [Ignore]
        public UserGroupData Data
        {
            get
            {
                if (_data == null)
                {
                    _data = new UserGroupData() { Id = Id, Name = Name, Role = Role, IsGameMaster = IsGameMaster, Servers = Servers };
                }
                return _data;
            }
        }
    }
}
