using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Stump.Server.AuthServer.Database
{
    [TableName("worlds_characters_deleted")]
    public class WorldCharacterDeleted : IAutoGeneratedRecord
    {
        public long Id
        {
            get;
            set;
        }
        public int CharacterId
        {
            get;
            set;
        }
        public DateTime DeletionDate
        {
            get;
            set;
        }
        public int AccountId
        {
            get;
            set;
        }
        public int WorldId
        {
            get;
            set;
        }
    }
}