using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.AuthServer.Database
{
    [TableName("worlds_characters")]
    public class WorldCharacter : IAutoGeneratedRecord
    {
        public long Id
        {
            get;
            set;
        }
        public int CharacterId
        {
            get;
            set;
        }
        public int AccountId
        {
            get;
            set;
        }
        public int WorldId
        {
            get;
            set;
        }
    }
}