using Stump.Core.Reflection;
using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Characters;
using Stump.Server.WorldServer.Database.Items;
using Stump.Server.WorldServer.Database.Items.Templates;
using Stump.Server.WorldServer.Game.Effects.Instances;
using Stump.Server.WorldServer.Game.Items;

namespace Stump.Server.WorldServer.Database.Breeds
{
	[TableName("breeds_items")]
	public class BreedItem : IAutoGeneratedRecord
	{
		public int Id
		{
			get;
			set;
		}
		public int BreedId
		{
			get;
			set;
		}
		public int ItemId
		{
			get;
			set;
		}
		public uint Amount
		{
			get;
			set;
		}
		public bool MaxEffects
		{
			get;
			set;
		}
		public PlayerItemRecord GenerateItemRecord(CharacterRecord character)
		{
			ItemTemplate itemTemplate = Singleton<ItemManager>.Instance.TryGetTemplate(this.ItemId);
			if (itemTemplate == null)
			{
				throw new System.InvalidOperationException(string.Format("itemId {0} doesn't exists", this.ItemId));
			}
			System.Collections.Generic.List<EffectBase> effects = Singleton<ItemManager>.Instance.GenerateItemEffects(itemTemplate, this.MaxEffects);
			return new PlayerItemRecord
			{
				Id = AutoAssignedRecord<PlayerItemRecord>.PopNextId(),
				OwnerId = character.Id,
				Template = itemTemplate,
				Stack = this.Amount,
				Position = CharacterInventoryPositionEnum.INVENTORY_POSITION_NOT_EQUIPED,
				Effects = effects
			};
		}
	}
}
