using Stump.Core.IO;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Breeds
{
    [D2OClass("Head", "com.ankamagames.dofus.datacenter.breeds", true), TableName("breeds_heads")]
	public class Head : IAutoGeneratedRecord, ISaveIntercepter, IAssignedByD2O
	{
		private short[] m_skins;
		private string m_skinsCSV;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		[Ignore]
		public short[] Skins
		{
			get
			{
				return this.m_skins;
			}
			set
			{
				this.m_skins = value;
                this.m_skinsCSV = value.ToCSV(",");
			}
		}
		public string SkinsCSV
		{
			get
			{
				return this.m_skinsCSV;
			}
			set
			{
				this.m_skinsCSV = value;
                this.m_skins = value.FromCSV<short>(",");
			}
		}
		public string AssetId
		{
			get;
			set;
		}
		public uint Breed
		{
			get;
			set;
		}
		public uint Gender
		{
			get;
			set;
		}
		public uint Order
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			Stump.DofusProtocol.Classes.Head head = (Stump.DofusProtocol.Classes.Head)d2oObject;
			this.Id = head.id;
			this.SkinsCSV = head.skins;
			this.AssetId = head.assetId;
			this.Breed = head.breed;
			this.Gender = head.gender;
			this.Order = head.order;
		}
		public void BeforeSave(bool insert)
		{
			this.m_skinsCSV = this.m_skins.ToCSV(",");
		}
	}
}
