using Stump.Core.Reflection;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Spells
{
	[D2OClass("SpellState", "com.ankamagames.dofus.datacenter.spells", true), TableName("spells_states")]
	public sealed class SpellState : IAutoGeneratedRecord, IAssignedByD2O
	{
		private string m_name;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public uint NameId
		{
			get;
			set;
		}
		public string Name
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_name) == null)
				{
					arg_23_0 = (this.m_name = Singleton<TextManager>.Instance.GetText(this.NameId));
				}
				return arg_23_0;
			}
		}
		public bool PreventsSpellCast
		{
			get;
			set;
		}
		public bool PreventsFight
		{
			get;
			set;
		}
		public bool Critical
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			Stump.DofusProtocol.Classes.SpellState spellState = (Stump.DofusProtocol.Classes.SpellState)d2oObject;
			this.Id = spellState.id;
			this.NameId = spellState.nameId;
			this.PreventsSpellCast = spellState.preventsSpellCast;
			this.PreventsFight = spellState.preventsFight;
		}
	}
}
