using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Spells
{
	[D2OClass("SpellBomb", "com.ankamagames.dofus.datacenter.spells", true), TableName("spells_bombs")]
	public sealed class SpellBombTemplate : IAutoGeneratedRecord, IAssignedByD2O
	{
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public int ChainReactionSpellId
		{
			get;
			set;
		}
		public int ExplodSpellId
		{
			get;
			set;
		}
		public int WallId
		{
			get;
			set;
		}
		public int InstantSpellId
		{
			get;
			set;
		}
		public int ComboCoeff
		{
			get;
			set;
		}

		public void AssignFields(object d2oObject)
		{
			SpellBomb spellBomb = (SpellBomb)d2oObject;
			this.Id = spellBomb.id;
			this.ChainReactionSpellId = spellBomb.chainReactionSpellId;
			this.ExplodSpellId = spellBomb.explodSpellId;
			this.WallId = spellBomb.wallId;
			this.InstantSpellId = spellBomb.instantSpellId;
			this.ComboCoeff = spellBomb.comboCoeff;
		}
	}
}
