using Stump.Core.Reflection;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.I18n;

namespace Stump.Server.WorldServer.Database.Spells
{
	[D2OClass("SpellType", "com.ankamagames.dofus.datacenter.spells", true), TableName("spells_types")]
	public sealed class SpellType : IAutoGeneratedRecord, IAssignedByD2O
	{
		private string m_name;
		private string m_shortName;
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public uint LongNameId
		{
			get;
			set;
		}
		public string LongName
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_name) == null)
				{
					arg_23_0 = (this.m_name = Singleton<TextManager>.Instance.GetText(this.LongNameId));
				}
				return arg_23_0;
			}
		}
		public uint ShortNameId
		{
			get;
			set;
		}
		public string ShortName
		{
			get
			{
				string arg_23_0;
				if ((arg_23_0 = this.m_shortName) == null)
				{
					arg_23_0 = (this.m_shortName = Singleton<TextManager>.Instance.GetText(this.ShortNameId));
				}
				return arg_23_0;
			}
		}
		public void AssignFields(object d2oObject)
		{
			Stump.DofusProtocol.Classes.SpellType spellType = (Stump.DofusProtocol.Classes.SpellType)d2oObject;
			this.Id = spellType.id;
			this.LongNameId = spellType.longNameId;
			this.ShortNameId = spellType.shortNameId;
		}
	}
}
