using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Startup
{
	[TableName("startup_actions")]
	public sealed class StartupActionRecord : IAutoGeneratedRecord
	{
		private System.Collections.Generic.List<StartupActionItemRecord> m_items;
		public int Id
		{
			get;
			set;
		}
		public string Title
		{
			get;
			set;
		}
		public string Text
		{
			get;
			set;
		}
		public string DescUrl
		{
			get;
			set;
		}
		public string PictureUrl
		{
			get;
			set;
		}
		[Ignore]
		public System.Collections.Generic.List<StartupActionItemRecord> Items
		{
			get
			{
				return this.m_items ?? new System.Collections.Generic.List<StartupActionItemRecord>();
			}
			set
			{
				this.m_items = value;
			}
		}
	}
}
