using Stump.Core.IO;
using Stump.Core.Reflection;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Database.Npcs.Replies;
using Stump.Server.WorldServer.Game.Actors.RolePlay.Npcs;
using System.Collections.Generic;
namespace Stump.Server.WorldServer.Database.Npcs
{
    [D2OClass("NpcMessage", "com.ankamagames.dofus.datacenter.npcs", true), TableName("npcs_messages")]
    public sealed class NpcMessage : IAutoGeneratedRecord, IAssignedByD2O
    {
        private System.Collections.Generic.IList<string> m_parameters;
        private string m_parametersCSV;
        private System.Collections.Generic.List<NpcReply> m_replies;

        [PrimaryKey("Id", false)]
        public int Id
        {
            get;
            set;
        }
        public uint MessageId
        {
            get;
            set;
        }
        public string ParametersCSV
        {
            get
            {
                return this.m_parametersCSV;
            }
            set
            {
                this.m_parametersCSV = value;
                this.m_parameters = value.FromCSV<string>("|");
            }
        }
        [Ignore]
        public System.Collections.Generic.IList<string> Parameters
        {
            get
            {
                return this.m_parameters;
            }
            set
            {
                this.m_parameters = value;
                this.ParametersCSV = value.ToCSV("|");
            }
        }
        public System.Collections.Generic.List<NpcReply> Replies
        {
            get
            {
                System.Collections.Generic.List<NpcReply> arg_23_0;
                if ((arg_23_0 = this.m_replies) == null)
                {
                    arg_23_0 = (this.m_replies = Singleton<NpcManager>.Instance.GetMessageReplies(this.Id));
                }
                return arg_23_0;
            }
        }

        public void AssignFields(object d2oObject)
        {
            Stump.DofusProtocol.Classes.NpcMessage npcMessage = (Stump.DofusProtocol.Classes.NpcMessage)d2oObject;
            this.Id = npcMessage.id;
            this.MessageId = npcMessage.messageId;

            this.m_parameters = new List<string>();
            this.m_parametersCSV = "";
            this.m_replies = new List<NpcReply>();
        }
    }
}
