using Stump.Core.IO;
using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.World.Maps
{
	[D2OClass("MapCoordinates", "com.ankamagames.dofus.datacenter.world", true), TableName("world_maps_coordinates")]
	public sealed class MapCoordinateRecord : IAutoGeneratedRecord, ISaveIntercepter, IAssignedByD2O
	{
		private int[] m_mapIds;
		private string m_mapIdsCSV;
		[PrimaryKey("CompressedCoords", false)]
		public uint CompressedCoords
		{
			get;
			set;
		}
		public string MapIdsCSV
		{
			get
			{
				return this.m_mapIdsCSV;
			}
			set
			{
				this.m_mapIdsCSV = value;
				this.m_mapIds = value.FromCSV<int>(",");
			}
		}
		[Ignore]
		public int[] MapIds
		{
			get
			{
				return this.m_mapIds;
			}
			set
			{
				this.m_mapIds = value;
				this.m_mapIdsCSV = value.ToCSV(",");
			}
		}
		public void AssignFields(object d2oObject)
		{
			MapCoordinates mapCoordinates = (MapCoordinates)d2oObject;
			this.CompressedCoords = mapCoordinates.compressedCoords;
			this.MapIds = mapCoordinates.mapIds.ToArray();
		}
		public void BeforeSave(bool insert)
		{
			this.m_mapIdsCSV = this.MapIds.ToCSV(",");
		}
	}
}
