using Stump.DofusProtocol.Classes;
using Stump.DofusProtocol.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.World.Maps
{
	[D2OClass("MapReference", "com.ankamagames.dofus.datacenter.world", true), TableName("world_maps_references")]
	public sealed class MapReferenceRecord : IAutoGeneratedRecord, IAssignedByD2O
	{
		[PrimaryKey("Id", false)]
		public int Id
		{
			get;
			set;
		}
		public uint MapId
		{
			get;
			set;
		}
		public int CellId
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			MapReference mapReference = (MapReference)d2oObject;
			this.Id = mapReference.id;
			this.MapId = mapReference.mapId;
			this.CellId = mapReference.cellId;
		}
	}
}
