using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items
{
	[TableName("characters_items_selled")]
	public class PlayerMerchantItemRecord : ItemRecord<PlayerMerchantItemRecord>, IAutoGeneratedRecord
	{
		private int m_ownerId;
		private uint m_price;
		public int OwnerId
		{
			get
			{
				return this.m_ownerId;
			}
			set
			{
				this.m_ownerId = value;
				base.IsDirty = true;
			}
		}
		public uint Price
		{
			get
			{
				return this.m_price;
			}
			set
			{
				this.m_price = value;
				base.IsDirty = true;
			}
		}
	}
}
