using Stump.DofusProtocol.Enums;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items
{
	[TableName("characters_items")]
	public class PlayerItemRecord : ItemRecord<PlayerItemRecord>, IAutoGeneratedRecord
	{
		private int m_ownerId;
		private CharacterInventoryPositionEnum m_position;
		public int OwnerId
		{
			get
			{
				return this.m_ownerId;
			}
			set
			{
				this.m_ownerId = value;
				base.IsDirty = true;
			}
		}
		public CharacterInventoryPositionEnum Position
		{
			get
			{
				return this.m_position;
			}
			set
			{
				this.m_position = value;
				base.IsDirty = true;
			}
		}
	}
}
