using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Items
{
	[TableName("taxcollectors_items")]
	public class TaxCollectorItemRecord : ItemRecord<TaxCollectorItemRecord>, IAutoGeneratedRecord
	{
		private int m_ownerId;
		public int OwnerId
		{
			get
			{
				return this.m_ownerId;
			}
			set
			{
				this.m_ownerId = value;
				base.IsDirty = true;
			}
		}
	}
}
